name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '11'  # Update version if needed

    - name: Compile Java
      run: |
        cd HolidayTravelVehicles
        javac *.java

    - name: Run Java Program
      run: |
        cd HolidayTravelVehicles
        java Main
